### ISSUE TITLE
Not working with Firefox 33

### ISSUE THREAD

**Issue by robertf** [palant/jsdeobfuscator#1]
With Firefox 33.1.1 under Windows 7 I only ever see the message 'No scripts to be displayed, try opening a website' for both compiled and executed scripts. I'm using version 1.6.4, which is the latest version at addons.mozilla.org. Is there a later version? I see that 26 days ago metadata.gecko was 'Marked compatible with Firefox 37 & Co.' but there don't seem to have been any substantive changes for 2 years or more. 
Thank you for making this very useful tool available.

**Comment by robertf** [comment]
Have you had a chance to look at this further? People are still trying 
the extension and then complaining that it doesn't work.

You mentioned that you'd publish a blog post - I haven't found one, 
perhaps you haven't had a chance yet?

Thanks.

**Comment by palant** [comment]
I finally managed to integrate the extension with both the new debugging API and Developer Tools. It isn't pretty yet and the functionality is still limited but at least it is working.

**Comment by robertf** [comment]
I'm delighted that you're working on it and having success! I've really missed having it.
I guess for now it's necessary to build it myself to try it? I've never tried that.

**Comment by palant** [comment]
Yes, if you want to try it you will have to build it (see README for instructions). Feel free to ask if you run into issues or want me to upload a build after all.

The visuals seem fine now, it's mostly functionality missing at this point:

* Track script execution in addition to compilation.
* Pause/resume capturing
* Clear list automatically when the tab reloads.
* Sorting by compilation/execution time
* Search

There is also a performance issue, adding to the list is currently very slow. This definitely needs to be fixed before release, as to the features - not sure yet which are mandatory for the release and which can be added later.

Debugging add-ons/browser won't work, this definitely won't be in any time soon - probably not going to be possible at all.

**Comment by palant** [comment]
This issue can be considered fixed now, with the new version being almost feature-complete. Some polishing would still be good before release, e.g. the scripts list has issues with overly long function/file names and it seems that the content script isn't always shut down correctly. The remaining big issue is the search functionality - using JS Deobfuscator without it on larger codebases seems impractical. Sorting on the other hand doesn't seem essential.
