### ISSUE TITLE
only monitoring one tab?

### ISSUE THREAD

**Issue by paleolith** [palant/jsdeobfuscator#2]
Instructions say it will monitor all tabs. But when I activate it, it only monitors the tab in which I activated it. What am I missing?

Also, how do I use "exclude scripts" and "include scripts"? I suppose this has to do with the magnifying glass, but when I click it, I see a prompt "filter scripts" and no clue how to use it. Perhaps if I were developing JS this would be obvious, but at the moment I'm just a user trying to figure out which tabs are JS-heavy.

Thanks.

**Comment by palant** [comment]
Sorry about taking so long to update instructions, done now.

The old instructions apply to the old (1.x) version. JavaScript Deobfuscator 2.0 pretty much had to be rewritten from scratch, see https://palant.de/2015/07/17/javascript-deobfuscator-reloaded. With the new JavaScript debugging API in Firefox it is no longer feasible to record all tabs, so the new version doesn't do it.

Note that for finding JS-heavy tabs you wouldn't be happy with the old version either - while it recorded code from the entire browser, there was no way to associate that code with individual tabs.

**Comment by paleolith** [comment]
Re: [jsdeobfuscator] only monitoring one tab? (#2)


Thanks for the reply and explanation ... I guess we just have to wait for new help from FF.

Edward

On Thursday, October 8, 2015, 2:51:51 PM, you wrote:




Sorry about taking so long to update instructions, done now.
The old instructions apply to the old (1.x) version. JavaScript Deobfuscator 2.0 pretty much had to be rewritten from scratch, see https://palant.de/2015/07/17/javascript-deobfuscator-reloaded. With the new JavaScript debugging API in Firefox it is no longer feasible to record all tabs, so the new version doesn't do it.
Note that for finding JS-heavy tabs you wouldn't be happy with the old version either - while it recorded code from the entire browser, there was no way to associate that code with individual tabs.

**Comment by robertf** [comment]
I'm very happy that jsdeobfuscator works again. I just want to say, 
though, that the old version wasn't _so_ bad for finding JS-heavy 
tabs. On a few occasions I was able to identify the culprit based on 
clues in the JS function names. It would be nice to have such an 
overall look again, but I understand from your explanation that it 
would be very difficult.

- Robert
