### ISSUE TITLE
Prettify Source fails when this extension is enabled.

### ISSUE THREAD

**Issue by AlexanderOMara** [palant/jsdeobfuscator#3]
This is a pretty neat plugin, but I've discovered a small conflict it creates with the developer tools. Namely, [the Prettify Source button](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Pretty-print_a_minified_file) does nothing when this extension is enabled.

![pp-before](https://mdn.mozillademos.org/files/7059/21-pp-before.png)

So basically I can't have this extension enabled all the time and have this useful feature enabled. Not the worst thing in the world, but clearly a bug.

**Comment by palant** [comment]
I've tried reproducing this but it looks very much that this DevTools feature is simply broken, regardless of JavaScript Deobfuscator. Not sure what happened there...

**Comment by AlexanderOMara** [comment]
Hmm, that is weird. The button doesn't seem to be working at all for me in Firefox 45.0.2 for some reason. I'll probably check to see if another addon is causing it later. The button does work fine in Firefox Developer Edition though, where I am no longer able to reproduce the issue, so perhaps the issue is now obsolete?

**Comment by palant** [comment]
I'll close this issue for now. Feel free to reopen if you can still reproduce the issue. As it looks right now, there is just something wrong with that feature. There isn't really any intersection point with JavaScript Deobfuscator.
