### ISSUE TITLE
Needs to be updated to support a now common way of obfuscation

### ISSUE THREAD

**Issue by JonasNo** [palant/jsdeobfuscator#8]
Example:
`var A9a=window;for(var g in A9a){if(g.length===((96,0x56)<(0x108,33)?4.21E2:0x174>=(117.0E1,145)?(0x5D,6):46.5E1<=(137,0xB)?(0xE0,99.7E1):(0xD9,86.7E1))&&g.charCodeAt((0xF4>(48.,46.)?(0x1D3,3):(0xC3,88.)))===((1.346E3,11.8E1)<=76?0x197:(0x1B5,79)<148?(139.,100):1.042E3>(107.0E1,1.417E3)?45.5E1:(32.6E1,14.46E2))&&g.charCodeAt(((13.,131)>(117.,13.74E2)?'k':(0x7F,34.1E1)<(9.93E2,0x199)?(0x5E,5):(64,93)>=0x1D5?(91.0E1,false):(0x243,115)))===((0x108,1.03E2)>(26.,8.84E2)?(143.,2):(60.30E1,1.)<=(47.2E1,0x4B)?(0x7C,119):(0x80,95.80E1))&&g.charCodeAt((132.<=(8.290E2,0x214)?(100,1):(43,0x212)<=80?"h":(0x17A,120.)))===((11.5E2,133)<=(85,75)?139.:13.10E1>(51.5E1,96.4E1)?(0.,"E"):(0x133,10.)<=(70,40.)?(74.,105):(4.11E2,118.))&&g.charCodeAt(((131.,5.36E2)>=41?(2.07E2,0):(0x105,0x1FD)))===(0x1F3<(0x9E,52.80E1)?(0xE6,119):(67,0)))break};var N8E={'T':"m",'u':"o",'z':"s",'A':"n",'J':"e",'H':"a",'k':"ge"};A9a[g][(N8E.u+N8E.A+N8E.T+N8E.J+N8E.z+N8E.z+N8E.H+N8E.k)]=function(event){var e=((13.31E2,0x1C8)>=0x141?(81,'c'):5.560E2>(0xBB,0x255)?64.:(81.5E1,13.20E1)),C='o',i=false,m="ed",B="os",n="l",h="sa",d="M",o="t",l="ply",v="ope",I="*",R="ag",U="ess",F="tM",W="po",y="i",D="p",w=1,N="vn",r="dm",p=0,b=((145,1.01E3)>=37?(0x18,2):(2.56E2,5.34E2)<(0xC2,29)?18.0E1:104.30E1<(8.4E2,10.06E2)?(139,'u'):(109,0x116)),j="data",Y="g",X="mes",G="c",L="ur",s=event[(N8E.z+N8E.u+L+G+N8E.J)],msg=event[event[(N8E.T+N8E.J+N8E.z+N8E.z+N8E.H+N8E.k)]?(X+N8E.z+N8E.H+Y+N8E.J):(j)];if(msg&&msg.length==b&&msg[p]==(N8E.H+r+N)){if(msg[w]==(D+y+N8E.A+Y)){s[(W+N8E.z+F+U+R+N8E.J)]((D+N8E.u+N8E.A+Y),I);}else{var nw=A9a[g][(v+N8E.A)][(N8E.H+D+l)](window,msg[w]);s[(D+N8E.u+N8E.z+o+d+N8E.J+N8E.z+h+Y+N8E.J)]((nw&&nw[(G+n+B+m)]==i)?C:e,I);}}};`

**Comment by palant** [comment]
The point of JavaScript Deobfuscator is merely showing you what code is running. It does perform code beautification but it won't modify code.

Either way, updates to JavaScript Deobfuscator are not going to happen: Mozilla disables support for legacy extensions as of Firefox 57 (to be released in November), and porting JavaScript Deobfuscator to Web Extensions platform isn't going to be possible. So putting any effort into it now is going to be a waste of time.
