### ISSUE TITLE
FF v57 'compat', but not yet a WebExtension?

### ISSUE THREAD

**Issue by pgnd** [palant/jsdeobfuscator#9]
Here

    https://github.com/palant/jsdeobfuscator/blob/master/metadata.gecko

you've declared 'compat' with FF57

    [compat]
    firefox=31.0/57.0

After install, it still appears as a 'legacy' extension in FF.

Not yet, then a full-fledged webextension?  Is that planned?

**Comment by palant** [comment]
No, this cannot be a Web Extension, the necessary APIs simply don't exist. You can use it on Firefox 57 if you change the `extensions.legacy.enabled` preference to `true`. Enjoy while you still can!

**Comment by kasper93** [comment]
Is it completely broken now on Nightly or there is a way to still run it?

**Comment by palant** [comment]
Completely broken I think.
